# config.py

# --- 有道智云短语音识别配置 ---
YOUDAO_ASR_URL = "https://openapi.youdao.com/asrapi"
YOUDAO_APP_KEY = "3a8cb43d7274b4be"  # 替换为您的应用ID
YOUDAO_APP_SECRET = "89pGYLzOMAgLnFTrdcjutVEcXJsaQo6L" # 替换为您的应用密钥
YOUDAO_ASR_RATE = 16000
WAVE_OUTPUT_FILENAME = "temp_recorded_audio.raw" # 原始上传文件

# --- 有道智云语音合成 (TTS) 配置 ---
YOUDAO_TTS_URL = "https://openapi.youdao.com/ttsapi"
YOUDAO_TTS_VOICE_NAME = "youxiaoqin" # 默认发音人：有小沁 (女, 中文)
# YOUDAO_APP_KEY 和 YOUDAO_APP_SECRET 会被TTS复用

# --- DeepSeek NLU 配置 ---
DEEPSEEK_API_URL = "https://api.deepseek.com/chat/completions"
DEEPSEEK_API_KEY = "sk-6e296264a8f24154982870f9a8efcb21" # 替换为您的 DeepSeek API Key
DEEPSEEK_MODEL = "deepseek-chat"

# --- TPU Model Configuration ---
TPU_MODEL_NAME = "rcModel_3"
TPU_CONF_THRES = 0.5
TPU_IOU_THRES = 0.65
TPU_IMAGE_WIDTH = 640
TPU_IMAGE_HEIGHT = 640
TPU_REMOTE_MODE = False
TPU_REMOTE_URL = '192.168.137.1'

# --- 硬件与全局配置 ---
STM32_SERIAL_PORT = "/dev/ttyUSB0"
STM32_SERIAL_BAUDRATE = 115200
SERIAL_TIMEOUT = 1
CAMERA_INDEX = 0
DETECTION_ENABLED = True

# --- 机械臂物理参数与行为配置 ---
PICK_HEIGHT = 62
DROP_HEIGHT_OFFSET = 30
ARM_HOME_POS_X, ARM_HOME_POS_Y, ARM_HOME_POS_Z = 0, -180, 200
ARM_RESET_TIME = 1500
ARM_TRANSLATE_X_STEP, ARM_TRANSLATE_Y_STEP, ARM_TRANSLATE_Z_STEP = 15, 15, 15
ARM_MOVE_TIME = 300
PUMP_ROTATE_SMALL_STEP = 15
TABLE_Z_PLANE = 50

# --- 字体配置 ---
CHINESE_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
CHINESE_FONT_SIZE = 16

# --- 机械臂状态定义 (常量) ---
ARM_STATE_IDLE = "IDLE"
ARM_STATE_RUNNING_TRAJECTORY = "RUNNING_TRAJECTORY"
ARM_STATE_PAUSED_TRAJECTORY = "PAUSED_TRAJECTORY"
ARM_STATE_HOMING = "HOMING"
ARM_STATE_MANUAL_MOVE = "MANUAL_MOVE"
ARM_STATE_PICKING_SUBMITTED = "PICKING_SUBMITTED"
ARM_STATE_PICKING_MOVE_TO_SUCK = "PICKING_MOVE_TO_SUCK"
ARM_STATE_PICKING_SUCKING = "PICKING_SUCKING"
ARM_STATE_PICKING_LIFTING = "PICKING_LIFTING"
ARM_STATE_PICKING_HOMING_AFTER = "PICKING_HOMING_AFTER"
ARM_STATE_LISTENING = "LISTENING"
ARM_STATE_RECOGNIZING_VOICE = "RECOGNIZING_VOICE"
ARM_STATE_UNDERSTANDING_NLU = "UNDERSTANDING_NLU"
ARM_STATE_MOVING_TO_PLACE = "MOVING_TO_PLACE"
ARM_STATE_PLACING_OBJECT = "PLACING_OBJECT"

# --- 预定义数据 ---
PREDEFINED_TRAJECTORY = [
    (50, -150, 180, 1200), (50, -200, 170, 1200), (0,  -200, 160, 1000),
    (-50,-180, 180, 1200),
    (50, -150, 180, 1200), (50, -200, 170, 1200), (0,  -200, 160, 1000),
    (ARM_HOME_POS_X, ARM_HOME_POS_Y, ARM_HOME_POS_Z, 1500)
]
TOTAL_TRAJECTORY_POINTS = len(PREDEFINED_TRAJECTORY)

PREDEFINED_PLACE_LOCATIONS = {
    "桌子左上角": {"x": -80, "y": -150, "z": TABLE_Z_PLANE + DROP_HEIGHT_OFFSET},
    "桌子中间": {"x": 0, "y": -200, "z": TABLE_Z_PLANE + DROP_HEIGHT_OFFSET},
    "桌子右上角": {"x": 80, "y": -150, "z": TABLE_Z_PLANE + DROP_HEIGHT_OFFSET},
    "桌子左边": {"x": -70, "y": -180, "z": TABLE_Z_PLANE + DROP_HEIGHT_OFFSET},
    "桌子右边": {"x": 70, "y": -180, "z": TABLE_Z_PLANE + DROP_HEIGHT_OFFSET},
    "默认放置区": {"x": ARM_HOME_POS_X + 20, "y": ARM_HOME_POS_Y + 20, "z": ARM_HOME_POS_Z - 50}
}